apiVersion: v1
kind: Service
metadata:
  name: trivy-service-definition
spec: 
  type: NodePort
  ports: 
    - targetPort: 4594
      port: 4594
      nodePort: 4594
  selector:
    app: trivy
    type: security
